pipeline {
        agent {
            label 'master'
        }

        stages {
            stage('Clean') {
                steps {
                    script {
                        sh "rm -rf out/organisations"
                    }
                }
            }

            stage('csvlint') {
                agent {
                        docker {
                            image 'gsscogs/csvlint'
                            reuseNode true
                            alwaysPull true
                        }
                    }

                steps {
                    script {
                        sh "ls -l"
                        sh "csvlint -s ./pipelines/organisations/schema.json"
                    }
                }
            }

            stage('csv2rdf') {
                agent {
                        docker {
                            image 'gsscogs/csv2rdf'
                            reuseNode true
                            alwaysPull true
                        }
                    }

                steps {
                    script {
                        sh "mkdir -p out/organisations"
                        sh "csv2rdf -t ./pipelines/organisations/organisations.csv -u ./pipelines/organisations/schema.json -m annotated > ./out/organisations/organisations.ttl"
                    }
                }
            }
        }
}

