@Library('pmd@csvwlib-build') _

csvw2pmd {
    csvwFilesDir = ["rdf-definitions/organisations","rdf-definitions/measures","rdf-definitions/attributes, rdf-definitions/concept-schemes"]
    shouldPublish = true
}